extends Node
var parametrs={
	"sword":{
		"HP":20,
		"speed":75,
		"command":-1,
		"type":0,
		"dmg":5,
		"attack_speed":2,
		"def":5,
		"money_to_enemy":5,
		"unit":"res://main/units/unit.tscn",
	},
	"bower":{
		"HP":15,
		"speed":100,
		"command":-1,
		"type":0,
		"dmg":7.5,
		"attack_speed":2,
		"def":5.5,
		"money_to_enemy":5,
		"unit":"res://main/units/bowers/bower.tscn",
	},
}
var bparametrs={
	"MBASE":{
		"money_to_enemy":100,
		"command":-1,
		"money":250,
		"battled_by":-1,
		"color":{
			"r":0,
			"g":0,
			"b":0,
			"a":0,
			},
		"name":"",
		"HP":200,
	},
	"sworders":{
		"money_to_enemy":25,
		"command":-1,
		"HP":100,
		"create_unit_time":10.0,
	},
	"bows":{
		"money_to_enemy":25,
		"command":-1,
		"HP":75,
		"create_unit_time":7.5,
	},
}
